# A required top-level key defining the services in your application
services:
  # Define your Node.js application as a web service
  - type: web
    name: gif-generator-api # A unique name for your service (you can change this)
    env: node                # Specify the environment type
    
    # Define the build command to run on the Render server
    buildCommand: |
      # 1. Update package lists and install system dependencies for node-canvas
      apt-get update && \
      apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev && \
      
      # 2. Run npm install (which now correctly compiles canvas against the new libraries)
      npm install
      
    # Define the command to start your application after the build is complete
    startCommand: node . #index.js 
    
    # The minimum required resources (recommended for initial deployment)
    plan: starter
    
    # The port your Node.js application listens on (default is 10000 on Render)
    # If your Express app uses process.env.PORT, this may not be needed, but it's safe to include.
    #port: 3000 