services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: |
      apt-get update && apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      npm run render-build
    startCommand: node .